### ISSUE TITLE
AttributeError: 'MjModel' object has no attribute 'eq_active'

### ISSUE THREAD

**Issue by pussinmood** [PierreMarza/task_conditioned_adaptation#2]
I tried to run eval.py,a new issue appeared like this:
Traceback (most recent call last):
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/oem/data/fb/新项目/task_conditioned_adaptation-main/src/run/eval.py", line 23, in <module>
    import dmc2gym, gym, mj_envs, mjrl.envs
  File "/home/oem/data/fb/新项目/eai-vc/third_party/dmc2gym/dmc2gym/__init__.py", line 56, in <module>
    e = make(domain_name='finger', task_name='spin', frame_skip=2)
  File "/home/oem/data/fb/新项目/eai-vc/third_party/dmc2gym/dmc2gym/__init__.py", line 52, in make
    return gym.make(env_id)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/envs/registration.py", line 676, in make
    return registry.make(id, **kwargs)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/envs/registration.py", line 520, in make
    return spec.make(**kwargs)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/gym/envs/registration.py", line 140, in make
    env = cls(**_kwargs)
  File "/home/oem/data/fb/新项目/eai-vc/third_party/dmc2gym/dmc2gym/wrappers.py", line 61, in __init__
    self._env = suite.load(
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/suite/__init__.py", line 113, in load
    return build_environment(domain_name, task_name, task_kwargs,
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/suite/__init__.py", line 148, in build_environment
    env = domain.SUITE[task_name](**task_kwargs)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/suite/finger.py", line 52, in spin
    physics = Physics.from_xml_string(*get_model_and_assets())
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 435, in from_xml_string
    return cls.from_model(model)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 418, in from_model
    return cls(data)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 122, in __init__
    self._reload_from_data(data)
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/mujoco/engine.py", line 399, in _reload_from_data
    model=index.struct_indexer(self.model, 'mjmodel', axis_indexers),
  File "/home/oem/anaconda3/envs/eai-vc/lib/python3.8/site-packages/dm_control/mujoco/index.py", line 623, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjModel' object has no attribute 'eq_active'

**Comment by PierreMarza** [comment]
This error might come from the version of _dm_control_ or _mujoco_ you have installed. Have you followed the installation guidelines in the README? What versions of _dm_control_ and _mujoco_ do you have?

**Comment by pussinmood** [comment]
dm_control==1.0.5,mujoco==3.2.2，i followed your installation guidelines in the README，then i fixed some lackness of my conda env ,i may did something wrong then.What version these two need to be?

**Comment by pussinmood** [comment]
i solved this problem by pip install mujoco==2.3.5,thanks for your patience for me
